service: cc-assignment-03-backend

custom:
  userTableName: users-${self:provider.stage}
  eventsTableName: events-${self:provider.stage}
  activeUsersTableName: active-users-${self:provider.stage}
  joinEventsTableName: join-events-${self:provider.stage}
  userImagesBucketName: cc-03-user-images-bucket-${self:provider.stage}
  serverless-offline:
    noPrependStageInUrl: true
  dynamodb:
    stages:
      - dev
    start:
      migrate: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - { 'Fn::GetAtt': ['usersTable', 'Arn'] }
            - { 'Fn::GetAtt': ['activeUsersTable', 'Arn'] }
            - { 'Fn::GetAtt': ['eventsTable', 'Arn'] }
            - { 'Fn::GetAtt': ['joinEventsTable', 'Arn'] }
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:PutObjectAcl
          Resource:
            - arn:aws:s3:::${self:custom.userImagesBucketName}/*
  environment:
    USERS_TABLE: ${self:custom.userTableName}
    EVENTS_TABLE: ${self:custom.eventsTableName}
    ACTIVE_USERS_TABLE: ${self:custom.activeUsersTableName}
    JOIN_EVENTS_TABLE: ${self:custom.joinEventsTableName}
    USER_IMAGES_BUCKET: ${self:custom.userImagesBucketName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.userTableName}
    eventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.eventsTableName}
    activeUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.activeUsersTableName}
    joinEventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
          - AttributeName: eventId
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
          - AttributeName: eventId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.joinEventsTableName}
    userImagesBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:custom.userImagesBucketName}

package:
  patterns:
    - '!.dynamodb'
