service: cc-assignment-03-backend

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
